### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by shmokmt** [kxxoling/waifu-cli#1]
Hi !
When `pip install waifu - cli` is executed, the following error will be displayed. How can I solve it?

```
Collecting waifu-cli
  Using cached https://files.pythonhosted.org/packages/ed/bb/972bfb2d1eeac679187c3f297a3a8770ae6125910fb546c196a52be3202c/waifu-cli-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5h/0z1p3pkn45q0ny30ffjn_3b80000gn/T/pip-install-0_279udv/waifu-cli/setup.py", line 3, in <module>
        from waifu import __version__ as version, description
      File "/private/var/folders/5h/0z1p3pkn45q0ny30ffjn_3b80000gn/T/pip-install-0_279udv/waifu-cli/waifu.py", line 33
        raise ValueError, 'scale should be 0, 1 or 2'
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5h/0z1p3pkn45q0ny30ffjn_3b80000gn/T/pip-install-0_279udv/waifu-cli/
```

**Comment by ghost** [comment]
Use `pip2` to install `waifu-cli` (i.e. `pip2 install waifu-cli`) as it appears this was written in Python 2 instead of Python 3.
